apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: secretz.bazinga.io
  namespace: meetup
spec:
  group: bazinga.io
  versions:
  - name: v1
    served: true
    storage: true
  scope: Namespaced
  names:
    plural: secretz
    singular: secret
    kind: Secret
    shortNames:
    - bs
  validation:
    openAPIV3Schema:
      required:
        - spec
      properties:
        spec:
          type: object
          required:
            - secretName
            - data
            - deployName
          properties:
            secretName:
              type: string
            data:
              items:
                type: string
            deployName:
              type: string