apiVersion: v1
kind: Service
metadata:
  name: coffee-shop-svc
  labels:
    app: coffee-webshop
    release: v1
  namespace: meetup
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: coffee-webshop
  type: NodePort