apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: meetup
spec:
  selector:
    app: nginx-front
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  type: NodePort
